lab04/bookstore/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root "products#index"
  resources :products
  resources :users
end

lab04/bookstore/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 

    if user.superadmin_role?
      can :manage, :all
      can :manage, :dashboard   
    end

    if user.admin_role?

      can :read, User, :id => user.id

    end
  end
end

lab04/bookstore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lab04/bookstore/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user



end

lab04/bookstore/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :product
end

lab04/bookstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:role])
  end
end

lab04/bookstore/app/controllers/products_controller.rb
class ProductsController < ApplicationController


  before_action :authenticate_user!

  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
  end

  def new 
    @product = Product.new

  end

  def create 
    @product = Product.new(product_params)
    
    if @product.save
      ProductNotifierMailer.new_product_mail.deliver_later
      redirect_to @product
    else
      @product.errors.full_messages
      # render :new, status: :unprocessable_entity 
    end  
  end 

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    
    if @product.update(product_params)
      redirect_to @product
    else
      render :new, status: :unprocessable_entity 
    end  
  
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end  

  private
    def product_params
      params.require(:product).permit(:name, :image, :price, :description,:user_id)
    end
end

lab04/bookstore/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to @user
    else
      render :new, status: :unprocessable_entity 
    end  
  
  end


  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

lab04/bookstore/app/helpers/application_helper.rb
module ApplicationHelper
end

lab04/bookstore/app/helpers/product_helper.rb
module ProductHelper
end

lab04/bookstore/app/helpers/user_helper.rb
module UserHelper
end

lab04/bookstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" integrity="sha512-t4GWSVZO1eC8BM339Xd7Uphw5s17a86tIZIj8qRxhnKub6WoyhnrxeCIMeAqBPgdZGlCcG2PrZjMc+Wr78+5Xg==" crossorigin="anonymous" referrerpolicy="no-referrer" />    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <div class="container">
      <%= yield %>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.min.js" integrity="sha512-3dZ9wIrMMij8rOH7X3kLfXAzwtcHpuYpEgQg1OA4QAob1e81H8ntUQmQm3pBudqIoySO5j0tHN4ENzA6+n2r4w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    </div>
  </body>
</html>

lab04/bookstore/app/views/products/_form.html.erb
<%= form_with model: product do |form| %>

    <div class="form-group mb-3">
        <%= form.label :name %>
        <%= form.text_field :name,class:"form-control" %>
        <% product.errors.full_messages_for(:name).each do |message| %>
            <div> <%= message %> </div>
        <% end %>    
    </div>
    
    <div class="form-group mb-3">
        <%= form.label :description %>
        <%= form.text_field :description,class:"form-control" %>
        <% product.errors.full_messages_for(:description).each do |message| %>
            <div> <%= message %> </div>
        <% end %>  
    </div>

    <div class="form-group mb-3">
      <%= form.label :price %> <br>
      <%= form.text_field :price,class:"form-control" %>
      <% product.errors.full_messages_for(:price).each do |message| %>
          <div> <%= message %> </div>
      <% end %>  
    </div>

    <div class="form-group mb-3">
      <%= form.label :image %> <br>
      <%= form.text_field :image,class:"form-control" %>
      <% product.errors.full_messages_for(:image).each do |message| %>
          <div> <%= message %> </div>
      <% end %>  
    </div>

    <div>
      <%= form.label :user_id %> <br>

        <%= form.collection_select :user_id, User.order(:name),:id,:name ,{}, {:class=>'form-control'}%>

    </div>


    <div class="mb-3">
    <%= form.submit  class: "btn btn-primary mt-3" %>
    <%= link_to "Back", :back,class:"btn btn-secondary mt-3" %>

    </div>
    
    
    <% end %>    

lab04/bookstore/app/views/products/edit.html.erb
<h1>Edit Product </h1>

<%= render "form", product: @product %>

lab04/bookstore/app/views/products/index.html.erb
<% if user_signed_in? %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

  <% if can? :manage, :dashboard %>
	  <%= link_to('Admin Panel', rails_admin.dashboard_path) %>
  <% end %>
<% else %>
  <%= link_to('Register', new_user_registration_path)  %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

<h1>Products</h1>

<%= link_to "New Product", new_product_path,class:"btn btn-primary mb-3" %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">description</th>
      <th scope="col">price</th>
      <th scope="col">creator</th>
      <th scope="col">action</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% @products.each do |product| %>
      <tr>
        <th scope="row"><%= product.id %></th>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to product.user.name, user_path(product.user) %></td>
        <td>
        <%= link_to "Show", product_path(product), class:"btn btn-secondary" %>
        <%= link_to "Edit", edit_product_path(product), class:"btn btn-info" %>
        <%= link_to "Destroy", product_path(product), class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                } %></li>

        
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

lab04/bookstore/app/views/products/new.html.erb
<h1>New Product </h1>

<%= render "form", product: @product %>

lab04/bookstore/app/views/products/show.html.erb
<h1> <%= @product.name %> </h1>
<p> <%= @product.description %> </p>
<p> <%= @product.price %> </p>
<img src="<%= @product.image %>" alt="image failed" ><br> 
<%= link_to "Back", :back,class:"btn btn-info mt-3" %>

lab04/bookstore/app/views/users/_form.html.erb
<%= form_with model: user do |form| %>

    <div class="form-group mb-3">
        <%= form.label :name %>
        <%= form.text_field :name,class:"form-control" %>
        <% user.errors.full_messages_for(:name).each do |message| %>
            <div> <%= message %> </div>
        <% end %>    
    </div>
    
    <div class="form-group mb-3">
        <%= form.label :email %>
        <%= form.text_field :email,class:"form-control" %>
        <% user.errors.full_messages_for(:email).each do |message| %>
            <div> <%= message %> </div>
        <% end %>  
    </div>


    <div class="mb-3">
    <%= form.submit  class: "btn btn-primary mt-3" %>
    <%= link_to "Back", :back,class:"btn btn-secondary mt-3" %>

    </div>
    
    
    <% end %>    

lab04/bookstore/app/views/users/edit.html.erb
<h1>Edit User </h1>

<%= render "form", user: @user %>

lab04/bookstore/app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<p> <%= @user.email %> </p>
<%= link_to "Back", :back,class:"btn btn-info mt-3" %>